//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.Orders = new HashSet<Order>();
        }

        public string oldPassword { get; set; }

        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int idUser { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p Tên")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Vui lòng nh?p tên th?t")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p H?")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Vui lòng nh?p h? th?t")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Vui lòng nh?p Email")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Vui lòng nh?p M?t kh?u")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$", ErrorMessage = "M?t kh?u t?i thi?u 8 kí t?, bao g?m 1 in hoa, 1 s? và 1 ký t? ??c bi?t")]
        public string Password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Vui lòng nh?p Nh?p l?i m?t kh?u")]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "M?t kh?u không trùng kh?p")]
        public string ConfirmPassword { get; set; }
        public string FullName()
        {
            return this.LastName + " " + this.FirstName;
        }

        public string Picture { get; set; }

        public string Address { get; set; }
        //[Required(ErrorMessage = "Vui lòng nh?p ngày sinh")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{mm/dd/yyyy}")]
        public Nullable<System.DateTime> NgaySinh { get; set; }

        public string CMT { get; set; }

        public string Sdt { get; set; }
        public int TichLuy { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
    public partial class EditProFile
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int idUser { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p Tên")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Vui lòng nh?p tên th?t")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p H?")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Vui lòng nh?p h? th?t")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p Email")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string Email { get; set; }
        public string FullName()
        {
            return this.LastName + " " + this.FirstName;
        }

        public string Picture { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p ??a ch?")]
        public string Address { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p s? ch?ng minh th?")]
        public string CMT { get; set; }
        [Required(ErrorMessage = "Vui lòng nh?p s? ?i?n tho?i")]
        public string Sdt { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }

    public partial class ChangePassword
    {
        public int idUser { get; set; }

        public string oldPassword { get; set; }

        [Required(ErrorMessage = "Vui lòng nh?p M?t kh?u")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$", ErrorMessage = "M?t kh?u t?i thiêu 8 kí t?, bao g?m 1 in hoa, 1 s? và 1 ký t? ??c bi?t")]
        public string Password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Vui lòng nh?p nh?p l?i m?t kh?u")]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "M?t kh?u không trùng kh?p")]
        public string ConfirmPassword { get; set; }
    }
}


